import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Suspense from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Časopis',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='fixed bg-white dark:bg-gray-700 border-red-700 min-w-full'>
          <div className='max-w-screen-xl flex flex-warp items-center justify-between mx-auto p-4 dark:text-white'>
            <div>
              there is no point to this text
            </div>
            <div>
              but it looks better with a navbar
            </div>
            <Link href="/">
              this one goes home
            </Link>
          </div>
        </nav>
          {children}
        </body>
    </html>
  )
}


